import { Order } from "@/app/_components/admin/tables/columns/orderColumn";

export const mockOrders: Order[] = [
		{
			id: '728ed52f',
			products: [
				{
					id: '1a2b3c',
					name: 'Product 1',
					price: 1000,
					images: ['https://picsum.photos/200/300'],
					cart: [],
					description: 'Product 1 description',
					isNovelty: true,
					stock: 10,
				},
				{
					id: '2a3b4c',
					name: 'Product 2',
					price: 500,
					images: ['https://picsum.photos/200/300'],
					cart: [],
					description: 'Product 2 description',
					isNovelty: false,
					stock: 5,
				},
			],
			status: 'cancelled',
			customer: 'Alice Smith',
			total: 1500,
		},
		{
			id: '829fe34d',
			products: [
				{
					id: '3a4b5c',
					name: 'Product 3',
					price: 750,
					images: ['https://picsum.photos/200/301'],
					cart: [],
					description: 'Product 3 description',
					isNovelty: false,
					stock: 8,
				},
			],
			status: 'pending',
			customer: 'Bob Johnson',
			total: 750,
		},
		{
			id: '930ge45f',
			products: [
				{
					id: '4a5b6c',
					name: 'Product 4',
					price: 2000,
					images: ['https://picsum.photos/200/302'],
					cart: [],
					description: 'Product 4 description',
					isNovelty: true,
					stock: 12,
				},
			],
			status: 'cancelled',
			customer: 'Catherine Williams',
			total: 2000,
		},
		{
			id: 'a12bc34d',
			products: [
				{
					id: '5a6b7c',
					name: 'Product 5',
					price: 300,
					images: ['https://picsum.photos/200/303'],
					cart: [],
					description: 'Product 5 description',
					isNovelty: false,
					stock: 20,
				},
			],
			status: 'success',
			customer: 'David Brown',
			total: 300,
		},
		{
			id: 'b23cd45e',
			products: [
				{
					id: '6a7b8c',
					name: 'Product 6',
					price: 100,
					images: ['https://picsum.photos/200/304'],
					cart: [],
					description: 'Product 6 description',
					isNovelty: false,
					stock: 15,
				},
			],
			status: 'pending',
			customer: 'Eva Green',
			total: 100,
		},
		{
			id: 'c34de56f',
			products: [
				{
					id: '7a8b9c',
					name: 'Product 7',
					price: 4000,
					images: ['https://picsum.photos/200/305'],
					cart: [],
					description: 'Product 7 description',
					isNovelty: true,
					stock: 3,
				},
			],
			status: 'cancelled',
			customer: 'Frank Miller',
			total: 4000,
		},
		{
			id: 'd45ef67g',
			products: [
				{
					id: '8a9b0c',
					name: 'Product 8',
					price: 2500,
					images: ['https://picsum.photos/200/306'],
					cart: [],
					description: 'Product 8 description',
					isNovelty: false,
					stock: 10,
				},
			],
			status: 'pending',
			customer: 'Grace Thompson',
			total: 2500,
		},
		{
			id: 'e56fg78h',
			products: [
				{
					id: '9a0b1c',
					name: 'Product 9',
					price: 850,
					images: ['https://picsum.photos/200/307'],
					cart: [],
					description: 'Product 9 description',
					isNovelty: true,
					stock: 25,
				},
			],
			status: 'pending',
			customer: 'Henry Scott',
			total: 850,
		},
		{
			id: 'f67gh89i',
			products: [
				{
					id: '0a1b2c',
					name: 'Product 10',
					price: 900,
					images: ['https://picsum.photos/200/308'],
					cart: [],
					description: 'Product 10 description',
					isNovelty: false,
					stock: 30,
				},
			],
			status: 'pending',
			customer: 'Isla White',
			total: 900,
		},
		{
			id: 'g78hi90j',
			products: [
				{
					id: '1a2b3d',
					name: 'Product 11',
					price: 1200,
					images: ['https://picsum.photos/200/309'],
					cart: [],
					description: 'Product 11 description',
					isNovelty: true,
					stock: 7,
				},
			],
			status: 'success',
			customer: 'Jack Turner',
			total: 1200,
		},
	];